name: eduapp_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  base_core:
    git:
      url: https://github.com/ByneappLLC/base_core.git
      ref: develop
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  injectable: ^2.1.1
  rxdart: ^0.27.0
  cached_network_image: ^3.2.3
  chopper: ^6.1.4
  cupertino_icons: ^1.0.2
  go_router: ^8.0.5
  path_provider: ^2.0.8
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.1.2
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.4
  chopper_generator: ^6.0.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.5
  json_serializable: ^6.3.1
  very_good_analysis: ^4.0.0+1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - .env